### PR TITLE
Audio is not getting routed to headphone/headset connected to 3.5 mm Jack Port

### PR DESCRIPTION
**Pull request by Sathish-Chandrasekaran-Pinayour**
Root-Cause : The default config routed audio to HDMI speakers.

Fix : Added changes to force route audio to 3.5 mm jack.

### CODE REVIEW

**Comment by anutriEximius** [comment]
+1

**Review by vinaykumar-eximius — APPROVED** [review]
+1

**Comment by vinaykumar-eximius** [comment]
Root-Cause : The default config routed audio to HDMI speakers.
Fix : Added changes to force route audio to 3.5 mm jack.

**Comment by vinaykumar-eximius** [comment]
Have created the pull request.

**Pull request merged**
